### ISSUE TITLE
Problem when mixing release build of rkcommon with debug build of ospray on Windows

### ISSUE THREAD

**Issue by nanzhang790** [ospray/rkcommon#4]
I'm developing an OSPRay based project. There are some issues with the OSPRay library so that I have to compile it in debug build on Windows, but I don't want to recompile every dependencies. Then, the OSPRay library has some problems during initialization, due to rkcommon's exported functions, where the std::string class is used as the APIs' parameters. This causes problems since the string class cannot be used in a mixed way across DLL boundaries. Could you please redesign the library to use char * only?

**Comment by johguenther** [comment]
`rkcommon` is inherently a C++ library, redesigning it to be C99 only won't be possible: it is not just `std::string`, `rkcommon::ParameterizedObject` is the base of all OSPRay objects, using advanced C++ features.

Some alternatives to ease development:
- use `RelWithDebInfo` instead of `Debug` for both rkcommon and OSPPray (this is how I work)
- or have two compiled versions of rkcommon (Debug and Release), and point OSPRay to the appropriate version when switching the build type
- or switch rkcommon as well when switching OSPRay &ndash; rebuilding of rkcommon is quite fast
